/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package atm_v1;

import atm_v1.processData.Customer;
import db.DBConnect;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author at01
 */
public class RutTien extends javax.swing.JFrame {
    static ArrayList<Customer> list;
     SingIn singin;
     public String stk = "";

    public RutTien() {
        initComponents();
        setLocationRelativeTo(null);
        this.setSize(630, 500);

        btn100k.setIcon(new ImageIcon("src/images/tru.png"));
        btn200k.setIcon(new ImageIcon("src/images/tru.png"));
        btn500k.setIcon(new ImageIcon("src/images/tru.png"));
        btn1Cu.setIcon(new ImageIcon("src/images/tru.png"));
        btn2Cu.setIcon(new ImageIcon("src/images/tru.png"));
        btn3Cu.setIcon(new ImageIcon("src/images/tru.png"));
        btnSoKhac.setIcon(new ImageIcon("src/images/kiemtra.png"));
        btnHuyGD.setIcon(new ImageIcon("src/images/exit.png"));

    }
    /**
     * Creates new form RutTien
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn500k = new javax.swing.JButton();
        btn1Cu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn100k = new javax.swing.JButton();
        btn200k = new javax.swing.JButton();
        btnSoKhac = new javax.swing.JButton();
        btnHuyGD = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSTK = new javax.swing.JTextField();
        btn3Cu = new javax.swing.JButton();
        btn2Cu = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn500k.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn500k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ngoisao.png"))); // NOI18N
        btn500k.setText("500.000VND");
        btn500k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500kActionPerformed(evt);
            }
        });

        btn1Cu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn1Cu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ngoisao.png"))); // NOI18N
        btn1Cu.setText("1.000.000VND");
        btn1Cu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1CuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("Quý Khách Vui Lòng Chọn Số Tiền Rút");

        btn100k.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn100k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ngoisao.png"))); // NOI18N
        btn100k.setText("100.000VND");
        btn100k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100kActionPerformed(evt);
            }
        });

        btn200k.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn200k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ngoisao.png"))); // NOI18N
        btn200k.setText("200.000VND");
        btn200k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn200kActionPerformed(evt);
            }
        });

        btnSoKhac.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSoKhac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.gif"))); // NOI18N
        btnSoKhac.setText("Số khác");
        btnSoKhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoKhacActionPerformed(evt);
            }
        });

        btnHuyGD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnHuyGD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        btnHuyGD.setText("Hủy Giao Dịch");
        btnHuyGD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyGDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Số TK:");

        txtSTK.setEditable(false);
        txtSTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSTKActionPerformed(evt);
            }
        });

        btn3Cu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn3Cu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ngoisao.png"))); // NOI18N
        btn3Cu.setText("3.000.000VND");
        btn3Cu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3CuActionPerformed(evt);
            }
        });

        btn2Cu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn2Cu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ngoisao.png"))); // NOI18N
        btn2Cu.setText("2.000.000VND");
        btn2Cu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2CuActionPerformed(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chuyentien.gif"))); // NOI18N
        jMenu1.setText("Rút Tiền ");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSTK, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn200k, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnSoKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHuyGD, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn500k, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(134, 134, 134)
                                        .addComponent(btn3Cu, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn2Cu, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn100k, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(134, 134, 134)
                                        .addComponent(btn1Cu, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSTK, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn100k, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1Cu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn200k, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2Cu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn500k, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSoKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHuyGD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btn3Cu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn500kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500kActionPerformed
        stk = txtSTK.getText();
        Date day = null;
        float sotienrut = 500000;
        float tongtien = 0;
        Connection con = null;
        ResultSet rs = null;
        CallableStatement cstmt = null;
        con = db.DBConnect.opConnection();
        try {
            cstmt = con.prepareCall("{call getCustomerId(?)}");
            cstmt.setString(1, stk);
            rs = cstmt.executeQuery();
            while (rs.next()) {
                cstmt = con.prepareCall("{call getCustomer}");
                tongtien = rs.getFloat("Money");
                tongtien = tongtien - sotienrut;
                if (tongtien >= 50000) {
                    cstmt = con.prepareCall("{call updateMoney(?,?)}");
                    cstmt.setString(1, txtSTK.getText());
                    cstmt.setFloat(2, tongtien);
                    int i = cstmt.executeUpdate();
                    if (i > 0) {
                        JOptionPane.showMessageDialog(null, "Rút iền thành công");
                        //  tien hanh lap bien lai
                        cstmt = con.prepareCall("{call insertHistory (?,?,?,?)}");
                        cstmt.setInt(1, 3);
                        cstmt.setString(2, stk);
                        cstmt.setDate(3, day);
                        cstmt.setFloat(4, sotienrut);
                        int k = cstmt.executeUpdate();
                        if (k > 0) {
                            if (JOptionPane.showConfirmDialog(null, "Bạn muốn nhận biên lai", "", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                                cstmt = con.prepareCall("{call getHistory}");
                                rs = cstmt.executeQuery();
                                while (rs.next()) {
                                    Object[] dt = {
                                        rs.getString("Sotaikhoan"),
                                        rs.getString("Id"),
                                        rs.getString("MaId"),
                                        rs.getString("Reason"),
                                        rs.getString("Sotien"),
                                        rs.getString("Date"),
                                        rs.getString("Content"),};
                                    ObjectOutputStream ghi = null;
                                    try {
                                        ghi = new ObjectOutputStream(new FileOutputStream("src/data/bienlai.txt"));
                                        ghi.writeObject(dt);
                                    } catch (IOException ex) {
                                        Logger.getLogger(RutTien.class.getName()).log(Level.SEVERE, null, ex);
                                    } finally {
                                        try {
                                            ghi.close();
                                        } catch (IOException ex) {
                                            Logger.getLogger(RutTien.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                    }

                                }
                            }

                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "SỐ tiền trong tài khoản không đủ!!!!");
                }

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Rút tiền không thành công!!!", "LOI", JOptionPane.ERROR_MESSAGE);
        } finally {
        }
    }//GEN-LAST:event_btn500kActionPerformed

    private void btn1CuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1CuActionPerformed
        stk = txtSTK.getText();
        Date day = null;
        float sotienrut = 1000000;
        float tongtien = 0;
        Connection con = null;
        ResultSet rs = null;
        CallableStatement cstmt = null;
        con = db.DBConnect.opConnection();
        try {
            cstmt = con.prepareCall("{call getCustomerId(?)}");
            cstmt.setString(1, stk);
            rs = cstmt.executeQuery();
            CallableStatement DBconnect;
            con = DBConnect.opConnection();
            while (rs.next()) {
                cstmt = con.prepareCall("{call getCustomer}");
                tongtien = rs.getFloat("Money");
                tongtien = tongtien - sotienrut;
                if (tongtien >= 50000) {
                    cstmt = con.prepareCall("{call updateMoney(?,?)}");
                    cstmt.setString(1, txtSTK.getText());
                    cstmt.setFloat(2, tongtien);
                    int i = cstmt.executeUpdate();
                    if (i > 0) {
                        JOptionPane.showMessageDialog(null, "Rút iền thành công");
                        //  tien hanh lap bien lai
                        cstmt = con.prepareCall("{call insertHistory (?,?,?,?)}");
                        cstmt.setInt(1, 3);
                        cstmt.setString(2, stk);
                        cstmt.setDate(3, day);
                        cstmt.setFloat(4, sotienrut);
                        int k = cstmt.executeUpdate();
                        if (k > 0) {
                            if (JOptionPane.showConfirmDialog(null, "Bạn muốn nhận biên lai", "", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                                cstmt = con.prepareCall("{call getHistory}");
                                rs = cstmt.executeQuery();
                                while (rs.next()) {
                                    Object[] dt = {
                                        rs.getString("Sotaikhoan"),
                                        rs.getString("Id"),
                                        rs.getString("MaId"),
                                        rs.getString("Reason"),
                                        rs.getString("Sotien"),
                                        rs.getString("Date"),
                                        rs.getString("Content"),};
                                    ObjectOutputStream ghi = null;
                                    try {
                                        ghi = new ObjectOutputStream(new FileOutputStream("src/data/bienlai.txt"));
                                        ghi.writeObject(dt);
                                    } catch (IOException ex) {
                                        Logger.getLogger(RutTien.class.getName()).log(Level.SEVERE, null, ex);
                                    } finally {
                                        try {
                                            ghi.close();
                                        } catch (IOException ex) {
                                            Logger.getLogger(RutTien.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                    }

                                }
                            } else {
                            }

                            giaodien gd = new giaodien();
                            gd.loadName(stk);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "SỐ tiền trong tài khoản không đủ!!!!");
                }

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Rút tiền không thành công!!!", "LOI", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btn1CuActionPerformed

    private void btn100kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100kActionPerformed
        stk = txtSTK.getText();
        Date day = null;
        float sotienrut = 100000;
        float tongtien = 0;
        Connection con = null;
        ResultSet rs = null;
        CallableStatement cstmt = null;
        con = db.DBConnect.opConnection();
        try {
            cstmt = con.prepareCall("{call getCustomerId(?)}");
            cstmt.setString(1, stk);
            rs = cstmt.executeQuery();
            while (rs.next()) {
                cstmt = con.prepareCall("{call getCustomer}");
                tongtien = rs.getFloat("Money");
                tongtien = tongtien - sotienrut;
                if (tongtien >= 50000) {
                    cstmt = con.prepareCall("{call updateMoney(?,?)}");
                    cstmt.setString(1, txtSTK.getText());
                    cstmt.setFloat(2, tongtien);
                    int i = cstmt.executeUpdate();
                    if (i > 0) {
                        JOptionPane.showMessageDialog(null, "Rút iền thành công");
                        //  tien hanh lap bien lai
                        cstmt = con.prepareCall("{call insertHistory (?,?,?,?)}");
                        cstmt.setInt(1, 3);
                        cstmt.setString(2, stk);
                        cstmt.setDate(3, day);
                        cstmt.setFloat(4, sotienrut);
                        int k = cstmt.executeUpdate();
                        if (k > 0) {
                            if (JOptionPane.showConfirmDialog(null, "Bạn muốn nhận biên lai", "", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                                cstmt = con.prepareCall("{call getHistory}");
                                rs = cstmt.executeQuery();
                                while (rs.next()) {
                                    Object[] dt = {
                                        rs.getString("Sotaikhoan"),
                                        rs.getString("Id"),
                                        rs.getString("MaId"),
                                        rs.getString("Reason"),
                                        rs.getString("Sotien"),
                                        rs.getString("Date"),
                                        rs.getString("Content"),};
                                    ObjectOutputStream ghi = null;
                                    try {
                                        ghi = new ObjectOutputStream(new FileOutputStream("src/data/bienlai.txt"));
                                        ghi.writeObject(dt);
                                    } catch (IOException ex) {
                                        Logger.getLogger(RutTien.class.getName()).log(Level.SEVERE, null, ex);
                                    } finally {
                                        try {
                                            ghi.close();
                                        } catch (IOException ex) {
                                            Logger.getLogger(RutTien.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                    }

                                }
                            } else {
                            }

                            giaodien gd = new giaodien();
                            gd.loadName(stk);

                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "SỐ tiền trong tài khoản không đủ!!!!");
                }

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Rút tiền không thành công!!!", "LOI", JOptionPane.ERROR_MESSAGE);
        }

        
    }//GEN-LAST:event_btn100kActionPerformed

    private void btn200kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn200kActionPerformed
        // TODO add your handling code here:
        stk = txtSTK.getText();
        Date day = null;
        float sotienrut = 200000;
        float tongtien = 0;
        Connection con = null;
        ResultSet rs = null;
        CallableStatement cstmt = null;
        con = db.DBConnect.opConnection();
        try {
            cstmt = con.prepareCall("{call getCustomerId(?)}");
            cstmt.setString(1, stk);
            rs = cstmt.executeQuery();
            while (rs.next()) {
                cstmt = con.prepareCall("{call getCustomer}");
                tongtien = rs.getFloat("Money");
                tongtien = tongtien - sotienrut;
                if (tongtien >= 50000) {
                    cstmt = con.prepareCall("{call updateMoney(?,?)}");
                    cstmt.setString(1, txtSTK.getText());
                    cstmt.setFloat(2, tongtien);
                    int i = cstmt.executeUpdate();
                    if (i > 0) {
                        JOptionPane.showMessageDialog(null, "Rút iền thành công");
                        //  tien hanh lap bien lai
                        cstmt = con.prepareCall("{call insertHistory (?,?,?,?)}");
                        cstmt.setInt(1, 3);
                        cstmt.setString(2, stk);
                        cstmt.setDate(3, day);
                        cstmt.setFloat(4, sotienrut);
                        int k = cstmt.executeUpdate();
                        if (k > 0) {
                            if (JOptionPane.showConfirmDialog(null, "Bạn muốn nhận biên lai", "", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                                cstmt = con.prepareCall("{call getHistory}");
                                rs = cstmt.executeQuery();
                                while (rs.next()) {
                                    Object[] dt = {
                                        rs.getString("Sotaikhoan"),
                                        rs.getString("Id"),
                                        rs.getString("MaId"),
                                        rs.getString("Reason"),
                                        rs.getString("Sotien"),
                                        rs.getString("Date"),
                                        rs.getString("Content"),};
                                    ObjectOutputStream ghi = null;
                                    try {
                                        ghi = new ObjectOutputStream(new FileOutputStream("src/data/bienlai.txt"));
                                        ghi.writeObject(dt);
                                    } catch (IOException ex) {
                                        Logger.getLogger(RutTien.class.getName()).log(Level.SEVERE, null, ex);
                                    } finally {
                                        try {
                                            ghi.close();
                                        } catch (IOException ex) {
                                            Logger.getLogger(RutTien.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                    }

                                }
                            } else {
                            }

                            giaodien gd = new giaodien();
                            gd.loadName(stk);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "SỐ tiền trong tài khoản không đủ!!!!");
                }

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Rút tiền không thành công!!!", "LOI", JOptionPane.ERROR_MESSAGE);
        } finally {
        }
    }//GEN-LAST:event_btn200kActionPerformed

    private void btnSoKhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoKhacActionPerformed
        // TODO add your handling code here:
        stk = txtSTK.getText();
        Connection con = null;
        ResultSet rs = null;
        CallableStatement cstmt = null;
        con = db.DBConnect.opConnection();
        try {
            cstmt = con.prepareCall("{call getCustomerId (?)}");
            cstmt.setString(1, stk);
            rs = cstmt.executeQuery();
            if (rs.next()) {
                RutTien rt = new RutTien();
                rt.loadrt(stk);
            }
            //
            //
            //
            //
        } catch (SQLException ex) {
            Logger.getLogger(giaodien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSoKhacActionPerformed

    private void btnHuyGDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyGDActionPerformed
        // TODO add your handling code here:
        stk = txtSTK.getText();
        Connection con = null;
        ResultSet rs = null;
        CallableStatement cstmt = null;
        con = db.DBConnect.opConnection();

        try {
            cstmt = con.prepareCall("{call getCustomerId (?)}");
            cstmt.setString(1, stk);
            rs = cstmt.executeQuery();
            if (rs.next()) {
                giaodien gdc = new giaodien();
                gdc.loadName(stk);

            }
            //
            //
            //
            //
        } catch (SQLException ex) {
            Logger.getLogger(giaodien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHuyGDActionPerformed

    private void btn3CuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3CuActionPerformed
        // TODO add your handling code here:
        stk = txtSTK.getText();
        Date day = null;
        float sotienrut = 3000000;
        float tongtien = 0;
        Connection con = null;
        ResultSet rs = null;
        CallableStatement cstmt = null;
        con = db.DBConnect.opConnection();
        try {
            cstmt = con.prepareCall("{call getCustomerId(?)}");
            cstmt.setString(1, stk);
            rs = cstmt.executeQuery();
            while (rs.next()) {
                cstmt = con.prepareCall("{call getCustomer}");
                tongtien = rs.getFloat("Money");
                tongtien = tongtien - sotienrut;
                if (tongtien >= 50000) {
                    cstmt = con.prepareCall("{call updateMoney(?,?)}");
                    cstmt.setString(1, txtSTK.getText());
                    cstmt.setFloat(2, tongtien);
                    int i = cstmt.executeUpdate();
                    if (i > 0) {
                        JOptionPane.showMessageDialog(null, "Rút iền thành công");
                        //  tien hanh lap bien lai
                        cstmt = con.prepareCall("{call insertHistory (?,?,?,?)}");
                        cstmt.setInt(1, 3);
                        cstmt.setString(2, stk);
                        cstmt.setDate(3, day);
                        cstmt.setFloat(4, sotienrut);
                        int k = cstmt.executeUpdate();
                        if (k > 0) {
                            if (JOptionPane.showConfirmDialog(null, "Bạn muốn nhận biên lai", "", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                                cstmt = con.prepareCall("{call getHistory}");
                                rs = cstmt.executeQuery();
                                while (rs.next()) {
                                    Object[] dt = {
                                        rs.getString("Sotaikhoan"),
                                        rs.getString("Id"),
                                        rs.getString("MaId"),
                                        rs.getString("Reason"),
                                        rs.getString("Sotien"),
                                        rs.getString("Date"),
                                        rs.getString("Content"),};
                                    ObjectOutputStream ghi = null;
                                    try {
                                        ghi = new ObjectOutputStream(new FileOutputStream("src/data/bienlai.txt"));
                                        ghi.writeObject(dt);
                                    } catch (IOException ex) {
                                        Logger.getLogger(RutTien.class.getName()).log(Level.SEVERE, null, ex);
                                    } finally {
                                        try {
                                            ghi.close();
                                        } catch (IOException ex) {
                                            Logger.getLogger(RutTien.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                    }

                                }
                            } else {
                            }

                            giaodien gd = new giaodien();
                            gd.loadName(stk);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "SỐ tiền trong tài khoản không đủ!!!!");
                }

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Rút tiền không thành công!!!", "LOI", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn3CuActionPerformed

    private void btn2CuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2CuActionPerformed
        // TODO add your handling code here:
        stk = txtSTK.getText();
        Date day = null;
        float sotienrut = 2000000;
        float tongtien = 0;
        Connection con = null;
        ResultSet rs = null;
        CallableStatement cstmt = null;
        con = db.DBConnect.opConnection();
        try {
            cstmt = con.prepareCall("{call getCustomerId(?)}");
            cstmt.setString(1, stk);
            rs = cstmt.executeQuery();
            while (rs.next()) {
                cstmt = con.prepareCall("{call getCustomer}");
                tongtien = rs.getFloat("Money");
                tongtien = tongtien - sotienrut;
                if (tongtien >= 50000) {
                    cstmt = con.prepareCall("{call updateMoney(?,?)}");
                    cstmt.setString(1, txtSTK.getText());
                    cstmt.setFloat(2, tongtien);
                    int i = cstmt.executeUpdate();
                    if (i > 0) {
                        JOptionPane.showMessageDialog(null, "Rút iền thành công");
                        //  tien hanh lap bien lai
                        cstmt = con.prepareCall("{call insertHistory (?,?,?,?)}");
                        cstmt.setInt(1, 3);
                        cstmt.setString(2, stk);
                        cstmt.setDate(3, day);
                        cstmt.setFloat(4, sotienrut);
                        int k = cstmt.executeUpdate();
                        if (k > 0) {
                            if (JOptionPane.showConfirmDialog(null, "Bạn muốn nhận biên lai", "", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                                cstmt = con.prepareCall("{call getHistory}");
                                rs = cstmt.executeQuery();
                                while (rs.next()) {
                                    Object[] dt = {
                                        rs.getString("Sotaikhoan"),
                                        rs.getString("Id"),
                                        rs.getString("MaId"),
                                        rs.getString("Reason"),
                                        rs.getString("Sotien"),
                                        rs.getString("Date"),
                                        rs.getString("Content"),};
                                    ObjectOutputStream ghi = null;
                                    try {
                                        ghi = new ObjectOutputStream(new FileOutputStream("src/data/bienlai.txt"));
                                        ghi.writeObject(dt);
                                    } catch (IOException ex) {
                                        Logger.getLogger(RutTien.class.getName()).log(Level.SEVERE, null, ex);
                                    } finally {
                                        try {
                                            ghi.close();
                                        } catch (IOException ex) {
                                            Logger.getLogger(RutTien.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                    }

                                }
                            } else {
                            }

                            giaodien gd = new giaodien();
                            gd.loadName(stk);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "SỐ tiền trong tài khoản không đủ!!!!");
                }

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Rút tiền không thành công!!!", "LOI", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn2CuActionPerformed

    private void txtSTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSTKActionPerformed
        // TODO add your handling code here:
        stk = txtSTK.getText();
        Connection con = null;
        ResultSet rs = null;
        CallableStatement cstmt = null;
        con = db.DBConnect.opConnection();
        try {
            cstmt = con.prepareCall("{call getCustomerId (?)}");
            cstmt.setString(1, stk);
            rs = cstmt.executeQuery();
            if (rs.next()) {
                RutTien rt = new RutTien();
                rt.loadrt(stk);
            }
          
        } catch (SQLException ex) {
            Logger.getLogger(giaodien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtSTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RutTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RutTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RutTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RutTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RutTien().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn100k;
    private javax.swing.JButton btn1Cu;
    private javax.swing.JButton btn200k;
    private javax.swing.JButton btn2Cu;
    private javax.swing.JButton btn3Cu;
    private javax.swing.JButton btn500k;
    private javax.swing.JButton btnHuyGD;
    private javax.swing.JButton btnSoKhac;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField txtSTK;
    // End of variables declaration//GEN-END:variables
void loadrt(String stk) {
        Connection con = null;
        ResultSet rs = null;
        CallableStatement cstmt = null;
        con = db.DBConnect.opConnection();
        try {
            cstmt = con.prepareCall("{call getCustomerId(?)}");
            cstmt.setString(1, stk);
            rs = cstmt.executeQuery();
            while (rs.next()) {
                cstmt = con.prepareCall("{call getCustomer}");
                txtSTK.setText(stk);

            }
        } catch (SQLException ex) {
            Logger.getLogger(SingIn.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
        }
    }


}
