/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Interface.Account;
import Interface.BankManager;
import Interface.Client;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
/**
 *
 */
public class BankUser extends javax.swing.JFrame {

    /**
     * Creates new form BankUser
     */
    public BankUser() {
        initComponents();
    }
    
    BankManager m_bankManager;
    Registry m_registry;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txa_printArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        txtAccountID = new javax.swing.JTextField();
        btnQrDatabase = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtAccIDtoDeposit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAmountToDeposit = new javax.swing.JTextField();
        btnDeposit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtAccIDtoWithDraw = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAmountToWithDraw = new javax.swing.JTextField();
        btnWithDraw = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bank User");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txa_printArea.setColumns(20);
        txa_printArea.setRows(5);
        jScrollPane1.setViewportView(txa_printArea);

        jLabel1.setText("ID Khách hàng");

        jLabel2.setText("ID Tài khoản");

        btnQrDatabase.setText("Tra cứu thông tin");
        btnQrDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQrDatabaseActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Tài khoản gửi tiền");

        jLabel4.setText("Số tiền gửi");

        btnDeposit.setText("Gửi tiền");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        jLabel5.setText("ID Tài khoản rút tiền");

        jLabel6.setText("Số tiền rút");

        btnWithDraw.setText("Rút tiền");
        btnWithDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithDrawActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btnQrDatabase))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(btnDeposit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtAccIDtoWithDraw, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAmountToWithDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(174, 174, 174)
                                    .addComponent(btnWithDraw)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtAccIDtoDeposit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(txtAccountID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCustomerID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAmountToDeposit))))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAccountID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnQrDatabase)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAccIDtoDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAmountToDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDeposit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAccIDtoWithDraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAmountToWithDraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnWithDraw)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try 
        {
            m_registry = LocateRegistry.getRegistry("localhost" ,1234);
            m_bankManager = (BankManager) m_registry.lookup("BankSystem");
        } 
        catch (NotBoundException notBoundException) 
        {
            System.out.println("Not Bound: " + notBoundException);
        } 
        catch (RemoteException remoteException) 
        {
            System.out.println("Remote Exception: " + remoteException);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnQrDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQrDatabaseActionPerformed
        // TODO add your handling code here:
        try
        {
            
            if(txtCustomerID.getText().length() > 0)
            {
                System.out.println("opps: " + txtCustomerID.getText() + "000");
                Client client = m_bankManager.getClient(txtCustomerID.getText());
                txtCustomerID.setText("");
                System.out.println("ID khách hàng được yêu cầu: " + client.getName());
                txa_printArea.setText("ID khách hàng được yêu cầu:: " + client.getName());
            }
            else 
            {
                if(txtAccountID.getText().length() > 0)
                {
                    Account account = m_bankManager.getAccount(txtAccountID.getText());
                    txtAccountID.setText("");
                    System.out.println("ID tài khoản yêu cầu: " +
                    account.getClient().getName());
                    txa_printArea.setText("ID tài khoản yêu cầu: " +
                    account.getClient().getName() + "\n Balance: " + account.getBalance());
                }
            }
            
        }
        catch (RemoteException remoteException) 
        {
            System.err.println(remoteException);
        }
    }//GEN-LAST:event_btnQrDatabaseActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        // TODO add your handling code here:
        try
        {
            if(txtAccIDtoDeposit.getText().length() > 0 && txtAmountToDeposit.getText().length() > 0)
            {
                m_bankManager.deposit(txtAccIDtoDeposit.getText(), Float.parseFloat(txtAmountToDeposit.getText()));
                Account account = m_bankManager.getAccount(txtAccIDtoDeposit.getText());
                txa_printArea.setText("Thông tin tài khoản :" + account.getClient().getName() + "\nSố dư: " + account.getBalance());
            }
        }
        catch (RemoteException remoteException) 
        {
            System.err.println(remoteException);
        }
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnWithDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithDrawActionPerformed
        // TODO add your handling code here:
        try
        {
            if(txtAccIDtoWithDraw.getText().length() > 0 && txtAmountToWithDraw.getText().length() > 0)
            {
                m_bankManager.withdraw(txtAccIDtoWithDraw.getText(), Float.parseFloat(txtAmountToWithDraw.getText()));
                Account account = m_bankManager.getAccount(txtAccIDtoWithDraw.getText());
                txa_printArea.setText("Thông tin tài khoản:" + account.getClient().getName() + "\nSố dư: " + account.getBalance());
            }
        }
        catch (RemoteException remoteException)
        {
            System.err.println(remoteException);
        }
    }//GEN-LAST:event_btnWithDrawActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnQrDatabase;
    private javax.swing.JButton btnWithDraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txa_printArea;
    private javax.swing.JTextField txtAccIDtoDeposit;
    private javax.swing.JTextField txtAccIDtoWithDraw;
    private javax.swing.JTextField txtAccountID;
    private javax.swing.JTextField txtAmountToDeposit;
    private javax.swing.JTextField txtAmountToWithDraw;
    private javax.swing.JTextField txtCustomerID;
    // End of variables declaration//GEN-END:variables
}
